---
title: "Visualising attributes of parole violators"
output: html_notebook
---


* Loading dataset

```{r}
parole <- read.csv("parole.csv")
parole$male <- as.factor(parole$male)
parole$state <- as.factor(parole$state)
parole$crime <- as.factor(parole$crime)
```

* Number of female parole violators

```{r}
table(parole$male, parole$violator)
```

* Most common crime in Kentucky

```{r}
table(parole$crime, parole$state == 2)
```

* Loading required libraries

```{r}
library(ggplot2)
```


* Basic histogram

```{r}
ggplot(aes(x = age), data = parole) +
  geom_histogram(binwidth = 5, boundary = 0, color = "black", fill = "cornflowerblue")
```


```{r}
ggplot(aes(x = age), data = parole) +
  geom_histogram(binwidth = 5, boundary = 0, color = "blue", fill = "cornflowerblue")
```

* Adding another dimension

```{r}
ggplot(data = parole, aes(x = age)) +
  geom_histogram(binwidth = 5) +
  facet_grid(male~.)
```

```{r}
ggplot(data = parole, aes(x = age)) +
  geom_histogram(binwidth = 5) +
  facet_grid(.~male)
```

```{r}
ggplot(data = parole, aes(x = age, fill = male)) +
  geom_histogram(binwidth = 5)
```


```{r}
colorPalette = c("#000000", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")
```

```{r}
ggplot(data = parole, aes(x = age, fill = male)) + geom_histogram(binwidth = 5) + scale_fill_manual(values=colorPalette)
```


```{r}
ggplot(data = parole, aes(x = age, fill = male)) + 
  geom_histogram(binwidth = 5, position = "identity", alpha = 0.5) + 
  scale_fill_manual(values=colorPalette)
```

* Time served

```{r}
ggplot(data = parole, aes(x = time.served)) +
  geom_histogram(binwidth = 1)
```

```{r}
ggplot(data = parole, aes(x = time.served)) +
  geom_histogram(binwidth = 0.1)
```

```{r}
ggplot(data = parole, aes(x = time.served)) +
  geom_histogram(binwidth = 1) +
  facet_grid(crime~.)
```


```{r}
ggplot(data = parole, aes(x = time.served, fill = crime)) + 
  geom_histogram(binwidth = 1, position = "identity", alpha = 0.5) + 
  scale_fill_manual(values=colorPalette)
```

