---
title: "Visualising network data"
output: html_notebook
---

* Loading datasets

```{r}
edges <- read.csv("edges.csv")
users <- read.csv("users.csv")
```

* Number of facebook users

```{r}
nrow(users)
```

* Average number of friends per user

```{r}
nrow(edges)*2/nrow(users)
```

* Most common locale

```{r}
table(users$locale, users$school)
```

* Summarizing the data

```{r}
table(users$school, users$ge)
```

* Creating a network

```{r}
library(igraph)
```

```{r}
g = graph.data.frame(edges, directed = FALSE, vertices = users)
```

```{r}
plot(g, vertex.size = 5, vertex.label = NA)
```

* Degree of nodes

```{r}
table(degree(g) >= 10)
```

* Important nodes

```{r}
V(g)$size = degree(g)/2 + 2
plot(g, vertex.label = NA)
```

```{r}
table(degree(g))
```

* Coloring vertices

```{r}
V(g)$color = "black"
V(g)$color[V(g)$gender == "A"] = "red"
V(g)$color[V(g)$gender == "B"] = "gray"
plot(g, vertex.label = NA)
```

```{r}
which.max(degree(g))
```

```{r}
users$gender[users$id == 4030]
```

* Coloring vertices based on the school that each user in our network attended

```{r}
V(g)$color = "black"
V(g)$color[V(g)$school == "A"] = "red"
V(g)$color[V(g)$school == "AB"] = "yellow"
```

```{r}
plot(g, vertex.label = NA)
```

```{r}
str(users$locale)
```

* Coloring vertices on the basis of locale

```{r}
V(g)$color = "black"
V(g)$color[V(g)$locale == "A"] = "red"
V(g)$color[V(g)$locale == "B"] = "yellow"
plot(g, vertex.label = NA)
```

